// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RedmondLoyaltyMiddleware.Models.InternalDB;

namespace RedmondLoyaltyMiddleware.Migrations
{
    [DbContext(typeof(MiddlewareDBContext))]
    [Migration("20200720060044_PromocodeAttemptStatus")]
    partial class PromocodeAttemptStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RedmondLoyaltyMiddleware.Models.InternalDB.PromocodePool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanUseManyTimes")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActual")
                        .HasColumnType("boolean");

                    b.Property<int>("UseCountRestriction")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PromocodePools");
                });

            modelBuilder.Entity("RedmondLoyaltyMiddleware.Models.InternalDB.PromocodeUseAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsNeedCreateNew")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Promocode")
                        .HasColumnType("text");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PromocodeUseAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
